inference_engine:
  ollama_llama: &ollama_llama
    class: OllamaInferenceEngine
    model_name_or_path: llama3.2
    credentials:
      api_url: OLLAMA_API_URL
    parameters:
      num_predict: 1000
      num_ctx: 8192
      temperature: 0.0
      repeat_penalty: 1
  
  ollama_guardian: &ollama_guardian
    class: OllamaInferenceEngine
    model_name_or_path: granite3-guardian:2b
    credentials:
      api_url: OLLAMA_API_URL
    parameters:
      num_predict: 1000
      num_ctx: 8192
      temperature: 0.0
      repeat_penalty: 1

  ollama_granite: &ollama_granite
    class: OllamaInferenceEngine
    model_name_or_path: granite3.2:8b
    credentials:
      api_url: OLLAMA_API_URL
    parameters:
      num_predict: 1000
      num_ctx: 8192
      temperature: 0.0
      repeat_penalty: 1

agents:
  BenchmarkAgent:
    ground_truth: gaf_guard/data/ground_truth/customer_complaints.json
  OrchestratorAgent:
    RiskGeneratorAgent:
      inference_engine: *ollama_granite
    HumanInTheLoopAgent:
      inference_engine: *ollama_granite
    StreamAgent:
      inference_engine: *ollama_granite
    RisksAssessmentAgent:
      inference_engine: *ollama_guardian
    DriftMonitoringAgent:
      inference_engine: *ollama_llama

run_configs:
  drift_threshold: 2
  risk_questionnaire_cot: gaf_guard/data/risk_questionnaire_cot.json
  risk_generation_cot: gaf_guard/data/risk_generation_cot.json
  drift_monitoring_cot: gaf_guard/data/drift_monitoring_cot.json
